services:

  db :
    image: postgres:17-alpine 
    # build: .  # <--- This tells Docker Compose to build from the Dockerfile!
    container_name: postgres_db2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: sh -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django_web
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - './.env'
    depends_on:
      - db
      
volumes:
  postgres_data:  
