# Generated by Django 5.1.6 on 2025-02-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepie_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo_path',
            field=models.TextField(max_length=200),
        ),
    ]
