# Generated by Django 5.1.6 on 2025-02-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepie_details', '0002_alter_recipe_photo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='photo_path',
        ),
    ]
